import type { Metadata } from "next";
import { Poppins, Nunito } from "next/font/google";
import Footer from "./components/Footer";
import { Icon } from "@iconify/react/dist/iconify.js";
import "./globals.css";
const nunito = Nunito({
  subsets: ["latin"],
  weight: ["300", "400", "800", "200", "500", "600", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${nunito.className} px-4 overflow-x-hidden `}>
        {children}
      </body>
    </html>
  );
}
